name: Problem Report
description: File a bug report.
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to help us make our works better and more stable!
  - type: input
    id: content
    attributes:
      label: Contact Details
      description: How may we get in touch if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result?
      description: If applicable, what did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Are there logs?
      description: If applicable, please provide logs.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: What's your environment?
      description: "If applicable, Please provide environment info: e.g., Chrome 102.0.5005.61, macOS 12.3.1 arm64)."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Do you accept the Code of Conduct?
      description: By submitting this report, you agree to follow our
        [Code of Conduct](https://github.com/teaminkling/.github/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: I agree to follow Inkling Interactive's Code of Conduct.
          required: true
